INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(VecCore_INCLUDE_DIR NAMES VecCore/VecCore HINTS ${ROOT_INCLUDE_DIR}/..)

SET( VecCore_INCLUDE_DIRS ${VecCore_INCLUDE_DIR})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(VecCore DEFAULT_MSG VecCore_INCLUDE_DIR )
