INCLUDE(FindPackageHandleStandardArgs)

FIND_PROGRAM( CheckMATE_EXECUTABLE NAMES CheckMATE HINTS ${CheckMATE_ROOT_DIR}/bin )

FIND_PACKAGE_HANDLE_STANDARD_ARGS( CheckMATE FOUND_VAR CheckMATE_FOUND REQUIRED_VARS CheckMATE_EXECUTABLE )
