INCLUDE(FindPackageHandleStandardArgs)

FIND_PROGRAM( CheckMATE_EXECUTABLE NAMES CheckMATE )

get_filename_component( CheckMATE_BIN_DIR "${CheckMATE_EXECUTABLE}" DIRECTORY )

find_file(CheckMATE_TESTFILE NAMES testfile.hep PATH_SUFFIXES bin/example_run_cards/auxiliary HINTS  ${CheckMATE_BIN_DIR}/.. )

FIND_PACKAGE_HANDLE_STANDARD_ARGS( CheckMATE FOUND_VAR CheckMATE_FOUND REQUIRED_VARS CheckMATE_EXECUTABLE CheckMATE_TESTFILE )
