INCLUDE(FindPackageHandleStandardArgs)

FIND_PROGRAM(MadGraph5_EXECUTABLE NAMES mg5_aMC HINTS ${MadGraph5_ROOT_DIR}/bin )

FIND_PACKAGE_HANDLE_STANDARD_ARGS( MadGraph5 FOUND_VAR MadGraph5_FOUND REQUIRED_VARS MadGraph5_EXECUTABLE )
	
