#!/usr/bin/env zsh
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=00:30:00 
#$ -l h_vmem=2G
#$-l site=hh 
#$ -w e
##$ -m ae -M prudent@physik.tu-dresden.de

whereIsSetup=WHERE_IS_SETUP
cp $whereIsSetup/setup.sh ./
source setup.sh


io=$fittinoPath/postProcessing/edgeDetection/


date
echo " --- Script started"

cd $TMP


echo " --- Copying input files and macros"

cp $io/EdgeDetection.C .
cp $io/EdgeDetection.h .
cp $io/ChainBuilder2.C .
cp $io/EdgeDetectionAlgorithm.C .
cp $io/edgeChain2 .
cp $io/edgeScript2 .

sed -i s/XXMINCHI2/VAR1/g EdgeDetection.C
sed -i s/XXMAXCHI2/VAR2/g EdgeDetectionAlgorithm.C EdgeDetection.C
sed -i s/XXINPUT/VAR3/g ChainBuilder2.C
sed -i s/XXOBS/VAR4/g ChainBuilder2.C
sed -i s/THEMODEL/VAR5/g EdgeDetection.h
sed -i s/XXMAXA0/VAR6/ EdgeDetection.C
sed -i s/XXMINA0/VAR7/ EdgeDetection.C
sed -i s/XXMAXM0/VAR8/ EdgeDetection.C
sed -i s/XXMINM0/VAR9/ EdgeDetection.C
sed -i s/XXMAXM12/VAR10/ EdgeDetection.C
sed -i s/XXMINM12/VAR11/ EdgeDetection.C
sed -i s/XXMAXTANBETA/VAR12/ EdgeDetection.C
sed -i s/XXMINTANBETA/VAR13/ EdgeDetection.C
sed -i s/XXMAXMASSTOP/VAR14/ EdgeDetection.C
sed -i s/XXMINMASSTOP/VAR15/ EdgeDetection.C



chmod u+x edgeScript2
./edgeScript2

#gzip *eps

output_dest=$output_PLOTS1D/VAR4/VAR3

if [ ! -d "$output_dest" ]; then
    mkdir -p $output_dest
fi


cp Splines.root Res* $output_dest


echo " --- Script finished"
date
