#!/usr/bin/env zsh
#
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=06:00:00 
#$-l site=hh 
#$ -w e
#$ -m ae -M $mymail

#----------------------------------
export ROOTSYS=/afs/naf.desy.de/products/root/amd64_rhel50/5.34.00
input_card1=$plotDir/XXOBS/XXMODEL/script_step1_XXOBS_XXMODEL
input_card2=$plotDir/XXOBS/XXMODEL/script_step2_XXOBS_XXMODEL
input_card3=$plotDir/XXOBS/XXMODEL/script_step3_XXOBS_XXMODEL
output_destination=$plotOutputDir/XXOBS/XXMODEL/
#-----------------------------------

export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH

echo "Script started"
date

cd $TMP
ini ROOT534

cp $fittinoPath/logo/fittinologoSPRING12.png .
cp $plotDir/arrange.sh .
chmod u+x arrange.sh

root -l -b < $input_card1
root -l -b < $input_card2
root -l -b < $input_card3

echo "Content..."
ls

echo "Copying output files to $output_destination"
cp * $output_destination

date 
echo "Script finished"
