#!/usr/bin/env zsh
#
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=12:00:00 
#$-l site=hh 
#$ -w e
##$ -m ae -M $mymail


whereIsSetup=WHERE_IS_SETUP
cp $whereIsSetup/setup.sh ./
source setup.sh


input_card1=$job_directory_PLOTS/XXOBS/XXMODEL/script_step1_XXOBS_XXMODEL
input_card2=$job_directory_PLOTS/XXOBS/XXMODEL/script_step2_XXOBS_XXMODEL
input_card3=$job_directory_PLOTS/XXOBS/XXMODEL/script_step3_XXOBS_XXMODEL

output_destination=$output_PLOTS/XXOBS/XXMODEL/

echo "Script started"
date

cd $TMP

cp $fittinoPath/logo/fittinologoSPRING12.png .
cp $working_directory/README/plots/arrange.sh .
chmod u+x arrange.sh

echo "Starting script 1"

root -l -b < $input_card1

echo "Starting script 2"

root -l -b < $input_card2

echo "Starting script 3"

root -l -b < $input_card3

echo "Content..."
ls


if [ ! -d $output_destination ]
    then
    mkdir -p $output_destination
fi


echo "Copying output files to $output_destination"
cp * $output_destination

date 
echo "Script finished"
