#!/bin/bash

# ####################################################
# Create the batch jobs
# ./makeJobsForMe
# 1: create the jobs
# 2: submit the jobs
# ####################################################

if [ ! -d $job_directory_PLOTS ]
    then
    mkdir $job_directory_PLOTS
fi

cd $job_directory_PLOTS

cp $working_directory/README/plots/ConvertMarkovChainHist2DtoContours2D.C .
cp $working_directory/README/plots/Plot2SigmaMarkovContours.C .

###################################
# Create the jobs

if [[ $1 == 1 ]]
    then


### ------------------------------
# Loop on the observables

    for obs in {0..17}; do

	echo ----- OBS $obs -----
	if [ ! -d $obs ]
	    then
	    mkdir $obs
	fi

### ------------------------------
# Loop on the models

	for model in CMSSM NUHM1 NUHM2; do

	    echo ..... $model .....
	    if [ ! -d $obs/$model ]
		then
		mkdir $obs/$model
	    fi

	    newMacro=step1\_$obs\_$model.C
	    cp $working_directory/README/plots/MakeMarkovChainContours2D.C $newMacro
	    sed -i s/XXOBS/$obs/g $newMacro
	    sed -i s/XXMODEL/$model/g $newMacro

	    cp $working_directory/README/plots/script_step1 script_step1\_$obs\_$model
	    cp $working_directory/README/plots/script_step2 script_step2\_$obs\_$model
	    cp $working_directory/README/plots/script_step3 script_step3\_$obs\_$model
	    sed -i s/XXOBS/$obs/g script_step1\_$obs\_$model 
	    sed -i s/XXOUTPUT/$outputForSed_BPR/g script_step1\_$obs\_$model
	    sed -i s/XXMODEL/$model/g script_step1\_$obs\_$model script_step2\_$obs\_$model script_step3\_$obs\_$model
	    sed -i s/XXPLOTDIR/$job_directoryForSed_PLOTS/g script_step1\_$obs\_$model script_step2\_$obs\_$model script_step3\_$obs\_$model

	    newJob=job_plot\_$obs\_$model
	    cp $working_directory/README/plots/job_plot $newJob
	    sed -i s/XXOBS/$obs/g $newJob
	    sed -i s/XXMODEL/$model/g $newJob
	    sed -i s/WHERE_IS_SETUP/$whereIsSetupForSed/g $newJob
	    chmod u+x $newJob

	    mv $newMacro $obs/$model
	    mv script_step*\_$obs\_$model $obs/$model
	    mv $newJob $obs/

	done
	
    done
fi




###################################
# Submit all jobs

if [[ $1 == 2 ]]
    then

    for obs in {0..17}; do
	for model in CMSSM NUHM1 NUHM2; do
	    newJob=job_plot\_$obs\_$model
	    cd $job_directory_PLOTS/$obs/
	    qsub $newJob
	done
    done

fi

