set( CMAKE_C_COMPILER @CMAKE_C_COMPILER@ CACHE FILEPATH "" )
set( CMAKE_CXX_COMPILER @CMAKE_CXX_COMPILER@ CACHE FILEPATH "" )
set( CMAKE_Fortran_COMPILER @CMAKE_Fortran_COMPILER@ CACHE FILEPATH "" )

set( CMAKE_INSTALL_PREFIX @Fittino_ROOT_DIR@ CACHE PATH "" )
set( CMAKE_PREFIX_PATH @totalPrefixPath@ CACHE PATH "" )
set( CMAKE_LIBRARY_PATH @libraryPath@ CACHE PATH "" )
set( CMAKE_INCLUDE_PATH @includePath@ CACHE PATH "" )

set( EIGEN3_INCLUDE_DIR @EIGEN3_INCLUDE_DIR@ CACHE PATH "" )
set( BOOST_INCLUDE_DIR @BOOST_INCLUDE_DIR@ CACHE PATH "" )
set( BOOST_LIBRARY_DIR @BOOST_LIBRARY_DIR@ CACHE PATH "" )

set( USE_PYTHON3 @USE_PYTHON3@ CACHE BOOL "" )
set( FEYNHIGGS_QUAD @FEYNHIGGS_QUAD@ CACHE PATH "" )

# todo: get rid of these
SET( SLHAEA_INSTALLATION_PATH @SLHAEA_INSTALLATION_PATH@ CACHE PATH "" )
SET( SModelS_ROOT_DIR @SModelS_ROOT_DIR@ CACHE PATH "" )
set( SModelSDatabase_ROOT_DIR @SModelSDatabase_ROOT_DIR@ CACHE PATH "" )
set( SPheno_ROOT_DIR @SPheno_ROOT_DIR@ CACHE PATH "" )

