set( CMAKE_C_COMPILER @CMAKE_C_COMPILER@ CACHE FILEPATH "" )
set( CMAKE_CXX_COMPILER @CMAKE_CXX_COMPILER@ CACHE FILEPATH "" )
set( CMAKE_Fortran_COMPILER @CMAKE_Fortran_COMPILER@ CACHE FILEPATH "" )

set( CMAKE_INSTALL_PREFIX @Fittino_ROOT_DIR@ CACHE PATH "" )
set( CMAKE_PREFIX_PATH @prefixPath@ CACHE PATH "" )
set( CMAKE_LIBRARY_PATH @libraryPath@ CACHE PATH "" )
set( CMAKE_INCLUDE_PATH @includePath@ CACHE PATH "" )

set( EIGEN3_INCLUDE_DIR @EIGEN3_INCLUDE_DIR@ CACHE PATH "" )
set( Boost_INCLUDE_DIR @Boost_INCLUDE_DIR@ CACHE PATH "" )
set( Boost_LIBRARY_DIR_RELEASE @Boost_LIBRARY_DIR_RELEASE@ CACHE PATH "" )
set( Boost_LIBRARY_DIR_DEBUG @Boost_LIBRARY_DIR_DEBUG@ CACHE PATH "" )
set( Boost_SYSTEM_LIBRARY_RELEASE @Boost_SYSTEM_LIBRARY_RELEASE@ CACHE FILEPATH "" )
set( Boost_SYSTEM_LIBRARY_DEBUG @Boost_SYSTEM_LIBRARY_DEBUG@ CACHE FILEPATH "" )
set( Boost_FILESYSTEM_LIBRARY_RELEASE @Boost_FILESYSTEM_LIBRARY_RELEASE@ CACHE FILEPATH "" )
set( Boost_FILESYSTEM_LIBRARY_DEBUG @Boost_FILESYSTEM_LIBRARY_DEBUG@ CACHE FILEPATH "" )
set( Boost_THREAD_LIBRARY_RELEASE @Boost_THREAD_LIBRARY_RELEASE@ CACHE FILEPATH "" )
set( Boost_THREAD_LIBRARY_DEBUG @Boost_THREAD_LIBRARY_DEBUG@ CACHE FILEPATH "" )
set( Boost_REGEX_LIBRARY_RELEASE @Boost_REGEX_LIBRARY_RELEASE@ CACHE FILEPATH "" )
set( Boost_REGEX_LIBRARY_DEBUG @Boost_REGEX_LIBRARY_DEBUG@ CACHE FILEPATH "" )
set( Boost_CHRONO_LIBRARY_RELEASE @Boost_CHRONO_LIBRARY_RELEASE@ CACHE FILEPATH "" )
set( Boost_CHRONO_LIBRARY_DEBUG @Boost_CHRONO_LIBRARY_DEBUG@ CACHE FILEPATH "" )

set( FEYNHIGGS_QUAD @FEYNHIGGS_QUAD@ CACHE PATH "" )

#set( SModelS_Tools_EXECUTABLE @SModelS_Tools_EXECUTABLE@ CACHE FILEPATH "" )
#set( SModelS_Database_DIR @SModelS_Database_DIR@ CACHE PATH "" )
# set( PYTHON_EXECUTABLE @PYTHON_EXECUTABLE@ CACHE FILEPATH "" )

# todo: get rid of these
set( GFORTRAN_LIBRARY_DIR @GFORTRAN_LIBRARY_DIR@ CACHE PATH "" )
set( MICROMEGAS_ROOT_DIR @MICROMEGAS_ROOT_DIR@ CACHE PATH "" )
set( SUPERISO_ROOT_DIR @SUPERISO_ROOT_DIR@ CACHE PATH "" )
set( SPheno_ROOT_DIR @SPheno_ROOT_DIR@ CACHE PATH "" )



