set( CMAKE_C_COMPILER @CMAKE_C_COMPILER@ CACHE FILEPATH "" )
set( CMAKE_CXX_COMPILER @CMAKE_CXX_COMPILER@ CACHE FILEPATH "" )
set( CMAKE_Fortran_COMPILER @CMAKE_Fortran_COMPILER@ CACHE FILEPATH "" )

set( CMAKE_INSTALL_PREFIX @Fittino_ROOT_DIR@ CACHE PATH "" )
set( CMAKE_PREFIX_PATH @totalPrefixPath@ CACHE PATH "" )

set( USE_PYTHON3 @USE_PYTHON3@ CACHE BOOL "" )

SET( SLHAEA_INSTALLATION_PATH @SLHAEA_INSTALLATION_PATH@ CACHE PATH "" )
SET( SModelS_ROOT_DIR @SModelS_ROOT_DIR@ CACHE PATH "" )
set( SModelSDatabase_ROOT_DIR @SModelSDatabase_ROOT_DIR@ CACHE PATH "" )
set( SPheno_ROOT_DIR @SPheno_ROOT_DIR@ CACHE PATH "" )
