set( INSTALL_SLHAea ON CACHE BOOL "" )
set( INSTALL_SPheno ON CACHE BOOL "" )
set( INSTALL_FeynHiggs OFF CACHE BOOL "" )
set( INSTALL_HiggsSignals OFF CACHE BOOL "" )
set( INSTALL_SuperIso OFF CACHE BOOL "" )
set( INSTALL_LHAPDF OFF CACHE BOOL "" )
set( INSTALL_MicrOMEGAs OFF CACHE BOOL "" )
set( INSTALL_HepMC2 OFF CACHE BOOL "" )
set( INSTALL_Pythia8 OFF CACHE BOOL "" )
set( INSTALL_Python ON CACHE BOOL "" )
set( INSTALL_MSSMTriLnV ON CACHE BOOL "" )
set( INSTALL_SModelS OFF CACHE BOOL "" )
set( INSTALL_SCYNet OFF CACHE BOOL "" )
set( INSTALL_CheckMATE OFF CACHE BOOL "" )
set( INSTALL_Fittino_Python2 OFF CACHE BOOL "" )
set( INSTALL_Fittino_Python3 ON CACHE BOOL "" )

set( CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "" )

# possible compiler settings for mac
# set( CMAKE_Fortran_COMPILER /opt/local/bin/gfortran-mp-5  CACHE PATH "" )
# set( GFORTRAN_LIBRARY_DIR /opt/local/lib/gcc5 CACHE PATH "" )
# set( CMAKE_CXX_COMPILER /usr/bin/clang++ CACHE PATH "" )
# set( CMAKE_C_COMPILER /usr/bin/clang CACHE PATH "" )
