#!/usr/bin/env zsh
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=03:00:00 
#$ -l h_vmem=1G
#$-l site=hh 
#$ -w e
##$ -m ae -M $mymail


whereIsSetup=WHERE_IS_SETUP
cp $whereIsSetup/setup.sh ./
source setup.sh

#----------------------------------
# Name of the fit to post-process or to study with toys (Attention, no .root at the end)
fit=FIT_TO_BE_PROCESSED

# Description of all observables
export OBSERVABLES=0

# Where does the input fit ntuple lies
input_directory=INPUT_DIR

# Which step of the post-processing to proceed (1=chi2 calculation,2=removal of buggy points)
export STEP=0

# Post-processing (1) or toy study (0)
export DATATOYS=1

# Do you want a 500GB file with all information (1=yes,0=no)?
export VERBOSE=0

input_file=$input_obs/fittino.in.point1.CMSSM.allObs.summer2012 #FIXME

#-----------------------------------


date
echo " --- Script started"

cd $TMP

echo " --- Copying input files and macros"

# General program
cp $working_directory/postProcessing.cc ./
cp $working_directory/postProcessing.h ./
cp $working_directory/compil ./

# libs
cp $tools_directory/libToyLHCChi2Provider.so ./

# Cleaning
cp $working_directory/cleaning.h ./

# Higgs
cp $working_directory/Higgs.h ./

# LHC
cp $tools_directory/ToyLHCChi2Provider.h ./
cp $tools_directory/signalGrids.root ./
cp $working_directory/LHC.h ./
cp $tools_directory/AllChi2Maps.root ./

# Astrofit
cp $working_directory/astrofit.h ./
cp $working_directory/dd_xenon100_2012.dat ./

# To extract the observables from the Fittino file
cp $working_directory/preparFittinoInput.sh ./

echo " --- Extracting observables from the Fittino input file"
chmod u+x preparFittinoInput.sh
cp $input_file ./
./preparFittinoInput.sh $input_file


echo " --- Compiling"
chmod u+x compil
./compil


echo " --- Running the macro"
# ls -lrth
# ldd -v libToyLHCChi2Provider.so
# ll /afs/naf.desy.de/group/atlas/software/lcg/external/gcc/4.3.2/lib64/libstdc++.so.6 

./postProcessing $fit $input_directory $output_MPR/XX

echo ""
echo " --- Copying output files"
cp $fit*cleaned.root $output_MPR/XX

echo " --- Script finished"
date
