#!/bin/bash

# ####################################################
# Create the batch jobs
# Takes one input:  the fit generation
# ####################################################


## Check the directories exist
if [ ! -d "$1" ]; then
    mkdir $1
fi

if [ ! -d "doublePointsRemoved/$1" ]; then
    mkdir doublePointsRemoved/$1
fi


### Create the file that will send all jobs to batch
batchAllJobs=batchAllJobs
if [ -e "$batchAllJobs" ]
    then
    rm $batchAllJobs
    touch $batchAllJobs
fi


### Loop over the fits
list=../listOfFits\_$1.txt
while read line
do
echo $line


### Create the new job script
newJob=job_multiplePointsRemoval\_$line
cp job_multiplePointsRemoval $newJob


### Adapt the new job script
sed -i s/FIT_TO_BE_PROCESSED/$line/g $newJob
if [ $1 -ge 3 -a $1 -le 8 ]
then
input="\/scratch\/hh\/current\/atlas\/users\/bechtle\/fittino\/fittino.out.summer2012\_0XX\/"
fi
if [ $1 -eq 9 ] 
then
input="\/scratch\/hh\/dust\/naf\/atlas\/user\/pbechtle\/fittino\/fittino.out.summer2012_0XX\/"
fi
if [ $1 -eq 10 -o $1 -eq 11 -o $1 -eq 12 -o $1 -eq 13 ]
then
input="\/scratch\/hh\/dust\/naf\/atlas\/user\/pbechtle\/fittino\/fittino.out.summer2012_XX\/"
fi
sed -i s/INPUT_DIR/$input/g $newJob
sed -i s/XX/$1/g $newJob


### Prepar for a global run in batch
echo "qsub $newJob" >> $batchAllJobs

done < $list


### Move all files
chmod u+x $batchAllJobs
mv job_multiplePointsRemoval_* $1/
mv batchAllJobs* $1/