#!/bin/bash

# ####################################################
# Check if the toy jobs succeeded by checking
# if the output exists
# takes as input: observables and model
# ####################################################


link=$output_TOYS/$1/$2

### Loop over toys and segmentation ###
itoy=0

### If your toys are segmentated in 1000 pieces each
for toy in {1..1000}
do
outFile=$link/$2\_final_toys$toy.root
if [ ! -e "$outFile" ]
then
let "itoy=$itoy+1"
#echo "qsub $1/$toy/job_$1_toys$toy\_seg$seg"
fi
done

echo  $itoy job missing
