#!/usr/bin/env zsh
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=06:00:00 
#$ -l h_vmem=2G
#$-l site=hh 
#$ -w e
#$ -m ae -M $mymail


#----------------------------------
# Name of the fit to post-process or to study with toys (Attention, no .root at the end)
fit=XXMODEL_final

# Fittino input file with the desired constraints to be applied -> THE MODEL DOES NOT MATTER !
input_file=$input_obs/fittino.in.point1.CMSSM.allObs.summer2012

# Where does the input fit ntuple lies
input_directory=$output_BPR/XXOBS/

# Output of post-processing and toys
output_destination=$output_TOYS/XXOBS/XXMODEL/

# Which step of the post-processing to proceed (1=chi2 calculation or toy,2=removal of buggy points)
export STEP=1

# Random seed for the toy
export RANDOM_SEED=XXTOY

# Do you want a 500GB file with all information (1=yes,0=no)?
export VERBOSE=0

# Post-processing (1) or toy study (0)
export DATATOYS=0

export OBSERVABLES=XXOBS

#-----------------------------------

export ROOTSYS=/afs/naf.desy.de/products/root/amd64_rhel50/5.28.00
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$tools_directory

date
echo " --- Script started"

cd $TMP
ini ROOT528

echo " --- Copying input files and macros"

# General program
cp $working_directory/postProcessing.cc .
cp $working_directory/postProcessing.h .
cp $working_directory/compil .

# Cleaning
cp $working_directory/cleaning.h .

# Higgs
cp $working_directory/Higgs.h .

# LHC
cp $working_directory/LHC.h .
cp $tools_directory/chi2Map_nObs_eq_nBgdExp.root .
cp $tools_directory/ToyLHCChi2Provider.h .
cp $tools_directory/signalGrids.root .

# Astrofit
cp $working_directory/astrofit.h .
cp $working_directory/dd_xenon100_2012.dat .

# To extract the observables from the Fittino file
cp $working_directory/preparFittinoInput.sh .

echo " --- Extracting observables from the Fittino input file"
chmod u+x preparFittinoInput.sh
cp $input_file .
./preparFittinoInput.sh $input_file


echo " --- Compiling"
chmod u+x compil
./compil


echo " --- Running the macro"
./postProcessing $fit $input_directory $output_destination

echo ""
echo " --- Copying output files"
rm *TEMP*.root
cp $fit*.root $output_destination

echo " --- Script finished"
date