#!/bin/bash

# ####################################################
# Create the batch jobs
# ./makeJobsForMe
# 1: make the toy jobs
# 2: submit the toy jobs
# 3: make the jobs for the extraction of the lowest chi2 point
# ####################################################


##################################
if [[ $1 == 1 ]]
then

for obs in {0..17}; do

echo ----- OBS $obs -----

for model in CMSSM NUHM1 NUHM2; do

echo ..... $model .....

for toy in {1..1000}
do
newJob=job_toys\_$obs\_$model\_toy$toy
cp job_toys $newJob

sed -i s/XXMODEL/$model/g $newJob
sed -i s/XXOBS/$obs/g $newJob
sed -i s/XXTOY/$toy/g $newJob
mv $newJob $obs/$model

done
done
done
fi

##################################
if [[ $1 == 2 ]]
then

for obs in {0..17}; do
for model in CMSSM NUHM1 NUHM2; do
newJob=job_toys\_$obs\_$model
cd $job_directory_TOYS/$obs/
qsub $newJob
done
done

fi

##################################
if [[ $1 == 3 ]]
then

for obs in {0..17}; do

echo ----- OBS $obs -----

for model in CMSSM NUHM1 NUHM2; do

echo ..... $model .....

newJob=job_extract\_$obs\_$model
cp job_extract $newJob

sed -i s/XXMODEL/$model/g $newJob
sed -i s/XXOBS/$obs/g $newJob
mv $newJob $obs/$model

done
done
fi
