#!/bin/bash

# ####################################################
# Create the batch jobs
# ./makeJobsForMe
# 1: make the jobs
# 2: submit the jobs
# ####################################################


###################################
if [[ $1 == 1 ]]
then

## Loop on observables and models
for obs in {0..17}; do

echo ----- OBS $obs -----
#mkdir $obs

for model in CMSSM NUHM1 NUHM2; do

echo ..... $model .....

#mkdir $obs/$model

## Copy the template job script and adapt it
newJob=job_bpr\_$obs\_$model
cp job_bpr $newJob
sed -i s/XXMODEL/$model/g $newJob
sed -i s/XXOBS/$obs/g $newJob
sed -i s/WHERE_IS_SETUP/$whereIsSetupForSed/g $newJob
mv $newJob $obs/

done

done
fi


###################################
if [[ $1 == 2 ]]
then

## Loop on observables and models
for obs in {0..17}; 
do
for model in CMSSM NUHM1 NUHM2; do
newJob=job_bpr\_$obs\_$model
cd $job_directory_BPR/$obs/
qsub $newJob
done
done

fi

