#!/usr/bin/env zsh
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=06:00:00 
#$ -w e
#$ -m ae -M prudent@physik.tu-dresden.de

# Submit this script to the batch with 'qsub job_postProcess_test'


#----------------------------------
# Name of the fit to post-process or to study with toys (Attention, no .root at the end)
fit=fittino.out.point1.CMSSM.HiggsObs.Summer2012_merged

# Fittino input file with the desired constraints to be applied
input_file=/afs/naf.desy.de/user/p/prudent/fittino/inputs/summer2012/fittino.in.point1.CMSSM.allObs.summer2012

# Where does the input fit ntuple lies
input_directory=/scratch/hh/current/atlas/users/bechtle/fittino/fittino.out.summer2012_01_probablyWrongGlobalHiggsChi2/

# Output of post-processing and toys
output_destination=/scratch/hh/current/atlas/users/prudent/fittino/postProcessing/postProcessing_2012/

# Where the processing programs lie
working_directory=/afs/naf.desy.de/user/p/prudent/fittino/postProcessing

# Where to retrieve the LHC chi2 tools from
tools_directory=/afs/naf.desy.de/user/p/prudent/fittino/tools/GetToyLHCChi2

# Number of toys to run
export NUMBERTOYS=0

# Do you want a 500MB file with all information (1=yes,0=no)?
export VERBOSE=0

# Post-processing (1) or toy study (0)
export DATATOYS=1
#-----------------------------------

export ROOTSYS=/afs/naf.desy.de/products/root/amd64_rhel50/5.26.00
export PATH=$ROOTSYS/bin:$PATH
export LD_LIBRARY_PATH=$ROOTSYS/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/afs/naf.desy.de/user/p/prudent/fittino/tools/GetToyLHCChi2

date
echo " --- Script started"

cd $TMP
ini ROOT526

echo " --- Copying input files and macros"

# General program
cp $working_directory/postProcessing.cc .
cp $working_directory/postProcessing.h .
cp $working_directory/compil .

# Cleaning
cp $working_directory/cleaning.h .

# Higgs
cp $working_directory/Higgs.h .

# LHC
cp $working_directory/LHC.h .
cp $tools_directory/ToyLHCChi2Provider.h .
histograms=$tools_directory/histograms.root
signalGrids=$tools_directory/signalGrids.root

# Astrofit
cp $working_directory/astrofit.h .
cp $working_directory/dd_xenon100_2012.dat .

# To extract the observables from the Fittino file
cp $working_directory/preparFittinoInput.sh .

echo " --- Extracting observables from the Fittino input file"
chmod u+x preparFittinoInput.sh
cp $input_file .
./preparFittinoInput.sh $input_file


echo " --- Compiling"
chmod u+x compil
./compil


echo " --- Running the macro"
./postProcessing $fit $input_directory $output_destination $histograms $signalGrids 

echo ""
echo " --- Copying output files"
cp $fit.root  $output_destination

echo " --- Script finished"
date