#!/bin/bash

# ####################################################
# Create the batch jobs
# Takes 1 input:  number of generation (3,4,5)
# ####################################################


rm $1/*
#rm ../outputs/$1/*.root


removeAll='removeAll'
if [ -e "$removeAll" ]
    then
    rm $removeAll
    touch $removeAll
fi

### Loop over fits ###

list=listOfFits\_$1.txt

while read line
do
#part=`echo $line | cut -d"X" -f 1`
echo $line

batchAllJobs=batchAllJobs\_$line
if [ -e "$batchAllJobs" ]
    then
    rm $batchAllJobs
    touch $batchAllJobs
fi

### Loop over segmentation ###
for seg in {1..100}
do
echo $seg
newJob=job_postProcessing\_$line\_seg$seg
cp job_postProcessing $newJob
sed -i s/FIT_TO_BE_PROCESSED/$line/g $newJob
sed -i s/XX/$1/g $newJob
sed -i s/YY/$seg/g $newJob
echo "qsub $newJob" >> $batchAllJobs
echo "rm $newJob.o*" >> $removeAll
chmod u+x $batchAllJobs

done
### seg

done < $list
### fits

chmod u+x $removeAll

mv job_postProcessing_* $1/
mv $removeAll $1/
mv batchAllJobs* $1/