#!/bin/bash

rm lance
touch lance
rm cleanLog
touch cleanLog
rm cleanAll
touch cleanAll

for (( job = 1 ; job <= 100 ; job++ ))
do
echo $job

rm job_postProcess_$job
cp job_postProcess job_postProcess_$job
sed -i s/OUTPUTDIR/"$job"/g job_postProcess_$job

rm -r $job/
mkdir $job/
echo "qsub job_postProcess_$job" >> lance
echo "rm job_postProcess_$job.o*" >> cleanLog
echo "rm job_postProcess_$job.o*" >> cleanAll
echo "rm -r $job/" >> cleanAll
echo "rm job_postProcess_$job" >> cleanAll
done

chmod u+x lance
chmod u+x cleanLog
chmod u+x cleanAll
