set( INSTALL_Fittino                         ON CACHE BOOL "" FORCE )
set( CMAKE_DISABLE_FIND_PACKAGE_PythonInterp ON CACHE BOOL "" FORCE )
set( CMAKE_DISABLE_FIND_PACKAGE_PythonLibs   ON CACHE BOOL "" FORCE )
