#!/bin/bash

# ####################################################
# Check if the jobs succeeded by checking
# if the output exists
# ####################################################


#### Observables sets ####
for obs in {0..17}
do
echo --------- OBS $obs --------
for fit in {3..13}
do

link=/scratch/hh/dust/naf/atlas/user/prudent/postProcessing_2012/outputs/$obs/$fit
ifit=0

### Loop over fits ###
while read line
do

JobOutput=$link/$line.root
if [ ! -e "$JobOutput" ]
then
#echo "qsub $fit/job_postProcessing\_$line\_seg$seg"
let "ifit=$ifit+1"
fi
done < listOfFits_$fit.txt

echo Fit $fit: $ifit job missing

done
done