#!/usr/bin/env zsh
#$ -j y
##$ -l os=sld5
#$ -cwd
#$ -P atlas
#$ -l h_cpu=HOUR:MINUTE:00 
#$ -l h_vmem=700M
#$-l site=hh 
#$ -w e
##$ -m ae -M $mymail

whereIsSetup=WHERE_IS_SETUP
cp $whereIsSetup/setup.sh ./
source setup.sh


#----------------------------------
# Name of the fit to post-process or to study with toys (Attention, no .root at the end)
fit=FIT_TO_BE_PROCESSED

# Description of all observables
input_file=$input_obs/fittino.in.point1.CMSSM.WHICH_OBS.summer2012
export OBSERVABLES=WHICH_OBS

# Where does the input fit ntuple lies
input_directory=$output_MPR/XX/

# Output of post-processing and toys
output_destination=$output_CHI2/WHICH_OBS/XX/

# Which step of the post-processing to proceed (1=chi2 calculation,2=removal of buggy points)
export STEP=1

# Post-processing (1) or toy study (0)
export DATATOYS=1

# Which segment of the PP (ntuple split to speed up)
# export NB_SEGMENT=100
# export PP_SEGMENT=YY

#-----------------------------------

date
echo " --- Script started"

cd $TMP

echo " --- Copying input files and macros"

# General program
cp $working_directory/postProcessing.cc .
cp $working_directory/postProcessing.h .
cp $working_directory/compil .

# libs
cp $tools_directory/libToyLHCChi2Provider.so ./


# Cleaning
cp $working_directory/cleaning.h .

# Higgs
cp $working_directory/Higgs.h .

# LHC
cp $tools_directory/ToyLHCChi2Provider.h .
cp $tools_directory/signalGrids.root .
cp $working_directory/LHC.h .
cp $tools_directory/AllChi2Maps.root .

# Astrofit
cp $working_directory/astrofit.h .
cp $working_directory/dd_xenon100_2012.dat .

# To extract the observables from the Fittino file
cp $working_directory/preparFittinoInput.sh .

echo " --- Extracting observables from the Fittino input file"
chmod u+x preparFittinoInput.sh
cp $input_file .
./preparFittinoInput.sh $input_file


echo " --- Compiling"
chmod u+x compil
./compil


echo " --- Running the macro"
./postProcessing $fit $input_directory $output_destination

echo ""
echo " --- Copying output files"
#rm *_cleaned.root

if [ ! -d "$output_destination" ]; then
    mkdir -p  $output_destination
fi

cp $fit*.root $output_destination

echo " --- Script finished"
date
