#!/bin/bash

##############################
# Input
# 1: make the jobs
# 2: send the jobs to batch
# 3: remove all batch scripts
##############################


#for obs in {0..17}
for obs in 17
  do
  echo ------ OBS $obs ------
  for fit in {3..13}
    do
    echo ....... $fit .......

    if [ $1 == 1 ]; then
	if [ ! -d "$job_directory_CHI2" ]; then
	    mkdir -p  $job_directory_CHI2
	fi
	cd $job_directory_CHI2
	cp $working_directory/README/calculationChi2/makeJobsForMe .
	cp $working_directory/README/calculationChi2/job_postProcessing .
	./makeJobsForMe $fit $obs
    fi

    if [ $1 == 2 ]; then
	cd $job_directory_CHI2/$obs/$fit/
	./batchAllJobs
    fi

    if [ $1 == 3 ]; then
	cd $job_directory_CHI2
	rm $obs/$fit/job_postProcessing_fittino.out.point*merged*
    fi


  done
done


